version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: taskmanager_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 190307Vi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
